# Generated by Django 4.2 on 2023-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_product_options_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                upload_to="uploads/products/img/", verbose_name="Изображение"
            ),
        ),
    ]
