# Generated by Django 4.2 on 2023-04-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Скидочная цена"
            ),
        ),
    ]
