# Generated by Django 4.2 on 2023-04-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_producttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.producttype",
                verbose_name="Тип товара",
            ),
        ),
    ]
