# Generated by Django 4.2 on 2023-04-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_product_product_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продуктов",
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="alternative_name",
            field=models.CharField(
                default=" ", max_length=50, verbose_name="Альтернативное название"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.producttype",
                verbose_name="Тип товара",
            ),
        ),
    ]
