# Generated by Django 4.2 on 2023-05-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_order_customer_order_city_order_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="house",
        ),
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="post_office",
        ),
        migrations.RemoveField(
            model_name="order",
            name="street",
        ),
        migrations.RemoveField(
            model_name="order",
            name="surname",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.customer",
                verbose_name="Заказчик",
            ),
        ),
    ]
