# Generated by Django 4.2 on 2023-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_customer_remove_order_city_remove_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=" ", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="house",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="post_office",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="surname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
