# Generated by Django 4.2 on 2023-05-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_customer_city_customer_email_customer_house_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("house", models.CharField(blank=True, max_length=50, null=True)),
                ("post_office", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улицы",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="house",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="post_office",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="street",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.customeraddress",
            ),
        ),
    ]
