# Generated by Django 4.2 on 2023-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_customer_address_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
            preserve_default=False,
        ),
    ]
