# Generated by Django 4.2.3 on 2023-08-09 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cartproduct_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
